### ISSUE TITLE
rhash verify too slow on windows

### ISSUE THREAD

**Issue by jack6th** [rhash/RHash#113] opened 2020-03-11 15:18 UTC
rhash-1.3.9-english-win32-2, Windows 10 64-bit 1903  
209 files in a folder about total 85MB.  
  
`rhash -rM dir_name > rhash.md5`  
0.27s  (rhash gen)  
`rhash -c rhash.md5`  
2.53s  (rhash verify) &#x1F534;   
`fciv -r dir_name -xml db.xml`  
0.33s  (microsoft fciv gen)  
`fciv -v -xml db.xml`  
0.29  (fciv verify)  
`tr -d "\r" < rhash.md5 > rhash_u.md5 && md5sum -c rhash_u.md5`  
0.29s  (msys2 md5sum verify)

**Comment by rhash** [comment] 2020-04-09 18:25
duplicate of #45

**Comment by jack6th** [comment] 2020-04-15 02:58
I read it.   Changing -c to -Mc fixed the problem.   
As #45 mentioned it should be written to the manual.

**Closed** 2020-04-15 02:58 UTC

**Comment by vb0** [comment] 2020-07-29 18:28
Run into the same, I've found first https://github.com/rhash/RHash/issues/45 from 2017. This is way more inefficient than it should be, there should be a warning if testing multiple algorithms, also this could be easily optimized to at least learn what was the right algorithm that matched and use that first for the next file.
