### ISSUE TITLE
checksum verify is still slow even when hash is specified 

### ISSUE THREAD

**Issue by Joey11904** [rhash/RHash#202] opened 2022-05-05 14:03 UTC
a (sort of) continuation of issue #45 
i tried running `rhash -c --md5 <checksum of file.txt>` and its still slow
but when i used `--no-detect-by-ext` along with the command above, the checksum verify is faster
i'm using rhash v1.4.2

Without `--no-detect-by-ext`:
```
$ time rhash -c --md5 random_100mb_file_checksum.txt 

--( Verifying random_100mb_file_checksum.txt )----------------------------------
random_100mb_file                                   OK 
--------------------------------------------------------------------------------
Everything OK

real    0m3.238s
user    0m3.205s
sys     0m0.028s
```

With `--no-detect-by-ext`:
```
$ time rhash -c --md5 --no-detect-by-ext random_100mb_file_checksum.txt 

--( Verifying random_100mb_file_checksum.txt )----------------------------------
random_100mb_file                                   OK 
--------------------------------------------------------------------------------
Everything OK

real    0m0.201s
user    0m0.170s
sys     0m0.030s
```

**Comment by rhash** [comment] 2022-05-17 20:46
Duplicate of #184. Already fixed by 79a1a0b3d267893c40ac31192b20e20969a3a79c.

**Closed** 2022-06-19 20:35 UTC
Labels: bug, duplicate
