### ISSUE TITLE
[feature thought] ignore updated/changed files on verification

### ISSUE THREAD

**Issue by znestor** [rhash/RHash#185] opened 2021-12-12 00:47 UTC
an option to ignore a hash change and still consider the file "OK" if both the hash and the mtime changed.

**Comment by rhash** [comment] 2022-06-19 23:15
Duplicate of #107, see also discussion #129.

The requested feature is implemented by the [RDChecksum](https://github.com/rdiez/Tools/tree/master/RDChecksum) script.

**Closed by rhash** 2022-06-19 23:15 UTC
Labels: FR
