### ISSUE TITLE
Question: Dealing with filenames containing newlines?

### ISSUE THREAD

**Issue by myxal** [rhash/RHash#191] opened 2022-01-17 21:13 UTC
Cheers. I'm trying to use rhash to verify correct copies of various backup data (home folders with AppData, old saved webpages etc) which for one reason or another contain files with newlines in the middle. Is there a recommended way of dealing with these filenames? As in, how to create a sum file that will subsequently verify these files.

My first thought was to use `--printf` to replicate the oft-used `-0` switch from `find` and many other tools, but if I'm reading the manual correctly, rhash isn't actually able to process sum files created with the printf option. Is there some other way?

**Comment by rhash** [comment] 2022-01-20 09:10
Hello. As I understand your OS is Windows.
Could you describe steps to create such files, to reproduce the situation?

There is a FR #97 to support special symbols in the filenames, and it is partly implemented (only verification part) by 757942e2d68c4527d37b8a6310d2dbf781d9225b.
But, unitl now, I thought that the problem was only Linux/Unix-related.
To support Windows, we need a corresponding test-case.

**Comment by myxal** [comment] 2022-01-20 09:50
> As I understand your OS is Windows.

No, actually. Oh, was it my reference to "AppData"? Sorry for the confusion, I use "AppData" as a shorthand for "any files created by applications after installation, and not explicitly named/saved by the user, regardless of OS" - savegames, browser profiles, logs, etc. The files in question were indeed created on Linux, by Google Earth, going by the paths. Don't take that as repro step, these are >10 year old backups and I no longer use Linux on the desktop to know/check if this behaviour still exists.

As for windows, though - IIRC NTFS drivers on Linux (ntfs-3g?) do not enforce Windows-style filename restrictions, which actually originate in the API (Win32?), not in the filesystem spec. So I think it would be possible to encounter such a file on windows after creating it in Linux. This is just a guess, though.

**Comment by rhash** [comment] 2022-06-19 20:45
Duplicate of #97.

**Closed by rhash** 2022-06-19 20:45 UTC
Labels: question
