### ISSUE TITLE
rhash is following symlinked directories even if the --follow option is not specified

### ISSUE THREAD

**Issue by tytso** [rhash/RHash#131] opened 2020-08-30 00:49 UTC
Reproduce by running the following in the top-level directory of the rhash sources

% ln -s /etc docs/etc
% rhash -r docs

Observe that rhash is trying to hash all of the etc directory, even though --follow option is not provided. 

What should have happened:

% ./rhash -r docs
; Generated by RHash v1.4.0 on 2020-08-29 at 20:49.24
; Written by Kravchenko Aleksey (Akademgorodok) - http://rhash.sf.net/
;
;         1877  19:48.34 2020-08-29 docs/CONTRIBUTING.md
;         3215  19:48.34 2020-08-29 docs/LIBRHASH.md
docs/CONTRIBUTING.md BA72845B
docs/LIBRHASH.md D66F30BA

**Comment by rhash** [comment] 2020-08-30 20:53
Thank you for reporting the bug and fixing it!

P.S. It seems, when accepting PR via Github UI (to mark it as accepted), Github forcefully rebases the commit instead of fast-forwarding it.

**Comment by taob** [comment] 2020-12-22 04:55
I'm seeing a "done" label on this issue, but the issue is still open. I am running 1.4.0 under Cygwin on Windows 10, and it appears the buggy behaviour is still present. When I specify -r to recurse through directories, it automatically enables --follow despite it not being present on the command line. I tried adding "follow=off" in the rhashrc, but to no effect.

**Comment by taob** [comment] 2020-12-22 04:59
Aha... while http://rhash.sourceforge.net/changelog.php does not show a release date for 1.4.0, I see on https://github.com/rhash/RHash/blob/master/ChangeLog that it was July 14, pre-dating this fix. I anxiously await the upcoming version then. :-)

**Comment by rhash** [comment] 2021-01-07 11:10
The fix is included into RHash v1.4.1.

**Closed by rhash** 2021-01-07 11:10 UTC
Labels: bug, done
