### ISSUE TITLE
Proposal to add an additional --printf formating directive to output a URL-encoded full path

### ISSUE THREAD

**Issue by ramayer** [rhash/RHash#20] opened 2016-01-17 03:59 UTC
Thanks for your excellent 'rhash' program.

I would find rhash even more useful for creating machine-readable output (such as tab-delimited files or JSON files) if it provided an option to output a URL-encoded version of the full path. 

The existing feature of URL-encoding a filename, along with the flexible --printf feature, gets close -- but it can still be problematic if you have a directory name with special characters like quotation marks, commas, or newlines.

I'd like to propose adding an additional --printf formatting directive that can output the URL-encoded full path.

(I have a working version of a patch here 94a930a4b54bd68735d70e13ddb75bc266665442 , and can submit a pull request for it.)

**Comment by ramayer** [comment] 2016-01-17 04:01
The pull request #21 adds such a feature.

**Comment by rhash** [comment] 2017-07-19 11:19
closing as duplicate of the pull request #21

**Closed by rhash** 2017-07-19 11:19 UTC
